baseurl = "https://example.com"
languageCode = "en"
defaultContentLanguage = "en"
title = "Hugo Theme Dream"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  # backgroundImage = "/me/background.jpg"
  # backgroundImageDark = "/me/background-dark.jpg"

  author = "Yue Yang"
  # description = ""
  avatar = "/img/avatar.jpeg"
  headerTitle = "Hugo Theme Dream"
  motto = "Motto"
  # headerBottomText = "" # deprecated

  # footerBottomText = ""

  # rss = true

  # utterancesRepo = ""

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  # VALINE_LANGUAGE = ""

  email = "g1enyy0ung@gmail.com"
  # twitter = ""
  # facebook = ""
  # instagram = ""
  # mastodon = ""
  # linkedin = ""
  # github = ""
  # stackoverflow = ""
  # codepen = ""

  siteStartYear = 2016

  # favicon = "/favicon.ico"

  # highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  # highlightjsExtraLanguages = ["ocaml"]
  # highlightjsTheme = "gruvbox-light"
  # highlightjsThemeDark = "gruvbox-dark"

  # options
  # showSummaryCoverInPost = true
  # hasTwitterEmbed = true
  # stickyNav = true
  # disableFlip = true
  # hideBackSocialLinks = true

  # [params.advanced]
  #   customCSS = ["css/custom.css"]
  #   customJS = []

  # [params.experimental]
  #   jsDate = true
  #   jsDateFormat = "yyyy年MM月dd日"
